jQuery.sap.registerPreloadedModules({
	"version": "2.0",
	"name": "ui5lab.wordcloud.library-preload",
	"modules": {
		"ui5lab/wordcloud/library.js": "/*!\n * ${copyright}\n */\nsap.ui.define([\"jquery.sap.global\",\"sap/ui/core/library\"],function(r,e){\"use strict\";return sap.ui.getCore().initLibrary({name:\"ui5lab.wordcloud\",dependencies:[\"sap.ui.core\"],interfaces:[],controls:[\"ui5lab.wordcloud.WordCloud\"],elements:[\"ui5lab.wordcloud.Word\"],noLibraryCSS:!1,version:\"${version}\"}),ui5lab.wordcloud});",
		"ui5lab/wordcloud/Word.js": "sap.ui.define([\"jquery.sap.global\",\"./library\",\"sap/ui/core/Element\"],function(e,t,i){\"use strict\";return i.extend(\"ui5lab.wordcloud.Word\",{metadata:{properties:{text:{type:\"string\"},weight:{type:\"int\",defaultValue:1},icon:{type:\"sap.ui.core.URI\"}}}})});",
		"ui5lab/wordcloud/WordCloud.js": "/*!\n * ${copyright}\n */\nsap.ui.define([\"jquery.sap.global\",\"./library\",\"sap/ui/core/Control\"],function(e,a,d){\"use strict\";return d.extend(\"ui5lab.wordcloud.WordCloud\",{metadata:{library:\"ui5lab.wordcloud\",properties:{rotate:{type:\"boolean\",defaultValue:!0},width:{type:\"sap.ui.core.CSSSize\",defaultValue:\"300px\"},height:{type:\"sap.ui.core.CSSSize\",defaultValue:\"300px\"},randomOrder:{type:\"boolean\",defaultValue:!1},colors:{type:\"string[]\",defaultValue:[\"#aec7e8\",\"#ff7f0e\",\"#ffbb78\",\"#2ca02c\",\"#98df8a\",\"#d62728\",\"#ff9896\",\"#9467bd\",\"#c5b0d5\",\"#8c564b\",\"#c49c94\",\"#e377c2\",\"#f7b6d2\",\"#7f7f7f\",\"#c7c7c7\",\"#bcbd22\",\"#dbdb8d\",\"#17becf\",\"#9edae5\"]},fontSizes:{type:\"string[]\",defaultValue:[22,26,28,32,36,40,44]}},aggregations:{words:{type:\"ui5lab.wordcloud.Word\",bindable:\"bindable\",cardinality:\"0..n\",singularName:\"Word\"}}},init:function(){}})});",
		"ui5lab/wordcloud/WordCloudRenderer.js": "/*!\n * ${copyright}\n */\nsap.ui.define([],function(){\"use strict\";var t={};return t.render=function(t,e){t.write(\"<div\"),t.writeControlData(e),t.addClass(\"ui5labWordCloud\"),t.addClass(\"tagCloud\"),t.writeClasses(),t.addStyle(\"width\",e.getWidth()),t.addStyle(\"height\",e.getHeight()),t.writeStyles(),t.write(\">\");var r=e.getFontSizes(),a=e.getColors(),i=e.getRotate(),o=e.getRandomOrder(),d=e.getWords();if(d&&d.length){var n=d.slice(),l=d.slice();n.sort(function(t,e){return e.getWeight()-t.getWeight()}),l.sort(function(t,e){return t.getWeight()-e.getWeight()});var s=n[0].getWeight(),g=l[0].getWeight(),h=[-1,0,1];o&&d.sort(function(t,e){return h[Math.floor(10*Math.random())%3]}),t.write(\"<ul\"),t.addClass(\"tagList\"),t.writeClasses(),t.write(\">\"),jQuery.each(d,function(e,o){t.write(\"<li>\");var d=Math.random()>.5?-1:1,n=0;i&&(n=d*(100*Math.random()%10));var l=Math.floor((o.getWeight()-g)/(s-g)*(r.length-1)),h=a[Math.floor(100*Math.random())%a.length],w=r[l]+6;t.write(\"<span\"),t.addStyle(\"font-size\",w+\"px\"),t.addStyle(\"color\",h),t.addStyle(\"-webkit-transform\",\"rotate(\"+n+\"deg)\"),t.addStyle(\"-ms-transform\",\"rotate(\"+n+\"deg)\"),t.addStyle(\"-moz-transform\",\"rotate(\"+n+\"deg)\"),t.addStyle(\"-o-transform\",\"rotate(\"+n+\"deg)\"),t.addStyle(\"display\",\"table-cell\"),t.addStyle(\"z-index\",e),t.writeStyles(),t.write(\">\"),o.getIcon()&&t.renderControl(new sap.ui.core.Icon({src:o.getIcon(),size:w+\"px\",color:h})),t.writeEscaped(o.getText()),t.write(\"</span>\"),t.write(\"</li>\")}),t.write(\"</ul>\")}t.write(\"</div>\")},t},!0);"
	}
});