jQuery.sap.registerPreloadedModules({
	"version": "2.0",
	"name": "ui5.sign.library-preload",
	"modules": {
		"ui5/sign/library.js": "sap.ui.define([\"jquery.sap.global\",\"sap/ui/core/library\"],function(i,e){\"use strict\";return i.sap.require(\"sap.ui.thirdparty.d3\"),sap.ui.getCore().initLibrary({name:\"ui5.sign\",dependencies:[\"sap.ui.core\"],types:[],interfaces:[],controls:[\"ui5.sign.Signature\"],elements:[],noLibraryCSS:!1,version:\"${version}\"}),ui5.sign});",
		"ui5/sign/Signature.js": "sap.ui.define([\"sap/ui/core/Control\",\"./library\"],function(t,e){\"use strict\";function n(){a=!0,u=[];var t=d3.select(d3.event.target);r=t.append(\"path\").data([u]).attr(\"fill\",\"none\").attr(\"stroke-linejoin\",\"round\").attr(\"stroke\",this.getPenColor()).attr(\"stroke-width\",this.getPenSize()).attr(\"d\",l)}function o(){a=!1}function i(){if(a){var t=d3.mouse(this);u.push({x:t[0],y:t[1]}),r.attr(\"d\",function(t){return l(t)})}}var r,s=t.extend(\"ui5.sign.Signature\",{metadata:{library:\"ui5.sign\",properties:{height:{type:\"sap.ui.core.CSSSize\",defaultValue:\"100%\"},width:{type:\"sap.ui.core.CSSSize\",defaultValue:\"100%\"},backgroundColor:{type:\"sap.ui.core.CSSColor\",defaultValue:\"rgb(221, 221, 221)\"},penColor:{type:\"sap.ui.core.CSSColor\",defaultValue:\"black\"},penSize:{type:\"int\",defaultValue:2},editable:{type:\"boolean\",defaultValue:!0}},aggregations:{},associations:{},events:{}},init:function(){},onBeforeRendering:function(){},onAfterRendering:function(){this.getEditable()&&this._attachEvents()},exit:function(){this._cleanUp()},_attachEvents:function(){var t=this._getD3SVG();t.on(\"mousedown\",n.bind(this)),t.on(\"mouseup\",o),t.on(\"mouseleave\",o),t.on(\"mousemove\",i),t.on(\"touchstart\",n.bind(this)),t.on(\"touchcancel\",o),t.on(\"touchend\",o),t.on(\"touchmove\",i)},setPenColor:function(t){return this.setProperty(\"penColor\",t,!0),this},setPenSize:function(t){return t<1&&jQuery.sap.log.error(\"Property 'penSize' cannot be less than 1\"),this.setProperty(\"penSize\",t,!0),this},_getD3SVG:function(){return d3.select(\"#\"+this.getId()).select(\"svg\")},_cleanUp:function(){this._getD3SVG().on(\"mousedown\",null),this._getD3SVG().on(\"mousemove\",null),this._getD3SVG().on(\"mouseup\",null),this._getD3SVG().on(\"mouseleave\",null),this._getD3SVG().on(\"touchstart\",null),this._getD3SVG().on(\"touchcancel\",null),this._getD3SVG().on(\"touchend\",null),this._getD3SVG().on(\"touchmove\",null)},getSVGString:function(){return d3.select(\"#\"+this.getId()).html()},setSVGString:function(t){return d3.select(\"#\"+this.getId()).node().innerHTML=t,this.setEditable(!1),this},setEditable:function(t){return this.setProperty(\"editable\",t,!0),t?this._attachEvents():this._cleanUp(),this},clear:function(){return this.rerender(),this}}),u=[],a=!1,l=d3.svg.line().interpolate(\"bundle\").tension(1).x(function(t){return t.x}).y(function(t){return t.y});return s});",
		"ui5/sign/SignatureRenderer.js": "sap.ui.define([],function(){\"use strict\";function t(t,e){t.write(\"<svg\");var i=e.getWidth()||\"auto\",r=e.getHeight()||\"auto\",o=e.getBackgroundColor();t.writeAttribute(\"width\",i),t.writeAttribute(\"height\",r),t.addStyle(\"background-color\",o),t.writeStyles(),t.write(\">\"),t.write(\"</svg>\")}var e={};return e.render=function(e,i){e.write(\"<div\"),e.writeControlData(i),e.writeStyles(),e.write(\">\"),t(e,i),e.write(\"</div>\")},e},!0);"
	}
});
